FROM oven/bun:1.1.13 AS builder

ENV NODE_ENV=development

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN bun run build

FROM oven/bun:1.1.13-slim AS runner

WORKDIR /app

COPY --from=builder /app/package.json ./package.json

COPY --from=builder /app/dist ./dist

ENV SERVER_PORT=3000

EXPOSE 3000

CMD ["bun", "run", "./dist/typesurvey.mjs"]