FROM oven/bun:1.1.13 AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN rsbuild build && \
    bun build --target=node --outfile=./dist/typesurvey.mjs ./server/app

FROM oven/bun:1.1.13-slim AS runner

WORKDIR /app

COPY --from=builder /app/package.json ./package.json

COPY --from=builder /app/dist ./dist

ENV SERVER_PORT=3000

EXPOSE 3000

CMD ["bun", "run", "./dist/typesurvey.mjs"]